"""Added category in expenses

Revision ID: af214072dfaa
Revises: fba20bcf11d2
Create Date: 2026-06-20 16:46:57.841825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af214072dfaa'
down_revision: Union[str, Sequence[str], None] = 'fba20bcf11d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_splits', sa.Column('category', sa.String(), nullable=True))
    op.add_column('group_expenses', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_expenses', 'category')
    op.drop_column('expense_splits', 'category')
    # ### end Alembic commands ###
